// Generated by CoffeeScript 2.5.1
(function () {
  var Adapter, r, test;
  test = require("tape");
  ({
    r
  } = require("renaissance"));
  Adapter = require("../../dist/Adapter");
  test("Adapter can be instantiated", t => {
    t.ok(new Adapter());
    return t.end();
  });
  test("Adapter has tmpl method", t => {
    var adapter;
    adapter = new Adapter();
    t.ok(typeof adapter.tmpl === "function");
    return t.end();
  });
  test("Adapter can be registered with renaissance", t => {
    t.ok(r.registerAdapter("appendHTML", Adapter));
    return t.end();
  });
}).call(this);